[project]
name = "base-station"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.119.1",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "uvicorn>=0.38.0",
]
